version: "3.7"
services:
  add_data_by_command:
    image: alpine
    volumes:
      - ./command:/command
    command: sh -c "sleep 5 && echo hello > /command/hello.txt"
  add_data_at_build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - vol:/test
    command: sleep 5
  copy:
    image: alpine
    volumes:
      - ./build:/build
      - vol:/test
    command: cp test/hello.txt build
    depends_on:
      - add_data_at_build
volumes:
  vol:
